name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Maven Build
        run: |
          mvn -B clean package
          mkdir -p staging
          cp target/*.jar staging/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging